#!/bin/bash

## NOTE: virtio-mmio currently only works when acpi is disabled
## maybe a bug in seabios+qemu not passing through the device data ?
## or is the kernel incapable of probing from acpi ?

. ./funcs.sh || exit 1

#QEMU_BIOS_TYPE="bios-microvm.bin"
QEMU_MACHINE="microvm"
QEMU_KVM="on"

qemu_bootparm_init
qemu_bootparm_kernel
qemu_bootparm_bios

#qemu_bootparm_rootfs

ROOTFS_IMAGE=`get_rootfs_image`
if [ "$ROOTFS_IMAGE" ]; then
    info "using root fs image: $ROOTFS_IMAGE"
    ROOT_DEVICE="/dev/vda"
    PARAMS+=("-drive" "id=vda,file=$ROOTFS_IMAGE,if=none")
    PARAMS+=("-device" "virtio-blk-device,drive=vda")
fi

PARAMS+=("-nographic")
PARAMS+=("-no-acpi")
PARAMS+=("-append" "root=$ROOT_DEVICE")
PARAMS+=("-monitor" "tcp:localhost:4444,server,nowait")
PARAMS+=("-device" "virtio-gpio-device,num-gpios=12,name=vgpio1,len-gpio-names=3,gpio-names[0]=wurst,gpio-names[1]=brot")
#PARAMS+=("-device" "virtio-gpio-device,num-gpios=12,name=vgpio1")

qemu_startup
